#!/usr/bin/env bash

# IMPORTANT:
#
# CLion will generate cmake-build-debug and cmake-build-release dirs,
# but the one to use is just `build`, generated by idf.

#set -x

port='/dev/ttyUSB0'
#port='/dev/ttyUSB1'
#port='/dev/ttyUSB2'

#baud=115200
#baud=$((115200 * 2))
#baud=460800
#baud=600000
baud=1500000

clear

printf '\n\nBuild\n'
. "$ESP_IDF_PATH"/export.sh || {
  exit 1
}

idf.py build || {
  exit 1
}

printf '\n\nFlash\n'
while ! idf.py flash -p "$port" -b $baud; do
  :;
done

printf '\n\nMonitor\n'
idf.py monitor -p "$port" || {
  exit 1
}
