#define GPIO_SEL_PIR_INSIDE GPIO_SEL_12
#define GPIO_NUM_PIR_INSIDE GPIO_NUM_12

#define GPIO_SEL_PIR_OUTSIDE GPIO_SEL_13
#define GPIO_NUM_PIR_OUTSIDE GPIO_NUM_13

#define GPIO_SEL_RELAY1 GPIO_SEL_14
#define GPIO_NUM_RELAY1 GPIO_NUM_14

#define GPIO_SEL_RELAY2 GPIO_SEL_27
#define GPIO_NUM_RELAY2 GPIO_NUM_27

#define GPIO_SEL_BEEP GPIO_SEL_15
#define GPIO_NUM_BEEP GPIO_NUM_15
